# BMAD V4 - Prometheus Configuration
# Owner: Alex Martinez (DevOps Lead)
# Created: 2025-10-21

# TODO: Configure Prometheus metrics
global:
  scrape_interval: 15s

scrape_configs:
  # TODO: Add scrape targets
