global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'bmad-backend'
    static_configs:
      - targets: ['backend:3550']
  - job_name: 'bmad-voice-agent'
    static_configs:
      - targets: ['voice-agent:3650']
